spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
		
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9292/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
